// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Neptune.Data;

namespace Neptune.Migrations
{
    [DbContext(typeof(DatabaseDbContext))]
    [Migration("20211024225836_Initiate")]
    partial class Initiate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("Neptune.Models.Option", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("archived")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("created")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<int>("datatype")
                        .HasColumnType("INTEGER");

                    b.Property<string>("description")
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("updated")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.ToTable("options");
                });

            modelBuilder.Entity("Neptune.Models.Parameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ParameterId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("archived")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("created")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<string>("description")
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("updated")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("ParameterId");

                    b.ToTable("parameter");
                });

            modelBuilder.Entity("Neptune.Models.Script", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("archived")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("created")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<string>("description")
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .HasColumnType("TEXT");

                    b.Property<string>("type")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("updated")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<string>("username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("username");

                    b.ToTable("scripts");
                });

            modelBuilder.Entity("Neptune.Models.User", b =>
                {
                    b.Property<string>("username")
                        .HasColumnType("TEXT");

                    b.Property<bool>("archived")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("created")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<string>("display_name")
                        .HasColumnType("TEXT");

                    b.Property<int>("permissions")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("updated")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.HasKey("username");

                    b.ToTable("user");
                });

            modelBuilder.Entity("OptionParameter", b =>
                {
                    b.Property<int>("optionsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("parameterId")
                        .HasColumnType("INTEGER");

                    b.HasKey("optionsId", "parameterId");

                    b.HasIndex("parameterId");

                    b.ToTable("OptionParameter");
                });

            modelBuilder.Entity("ParameterScript", b =>
                {
                    b.Property<int>("parameterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("scriptsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("parameterId", "scriptsId");

                    b.HasIndex("scriptsId");

                    b.ToTable("ParameterScript");
                });

            modelBuilder.Entity("Neptune.Models.Parameter", b =>
                {
                    b.HasOne("Neptune.Models.Parameter", null)
                        .WithMany("parameter")
                        .HasForeignKey("ParameterId");
                });

            modelBuilder.Entity("Neptune.Models.Script", b =>
                {
                    b.HasOne("Neptune.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("username");

                    b.Navigation("user");
                });

            modelBuilder.Entity("OptionParameter", b =>
                {
                    b.HasOne("Neptune.Models.Option", null)
                        .WithMany()
                        .HasForeignKey("optionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Neptune.Models.Parameter", null)
                        .WithMany()
                        .HasForeignKey("parameterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ParameterScript", b =>
                {
                    b.HasOne("Neptune.Models.Parameter", null)
                        .WithMany()
                        .HasForeignKey("parameterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Neptune.Models.Script", null)
                        .WithMany()
                        .HasForeignKey("scriptsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Neptune.Models.Parameter", b =>
                {
                    b.Navigation("parameter");
                });
#pragma warning restore 612, 618
        }
    }
}
